{{- $fullName := include "structurizr-local.fullname" . -}}
{{- if .Values.gatewayApi.create  -}}

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
spec:
  parentRefs:
  {{- if .Values.gatewayApi.gateway.create  }}
    - name: {{ $fullName }}
  {{- else -}}
    - name: {{ .Values.gatewayApi.gateway.name }}
      namespace: {{ .Values.gatewayApi.gateway.namespace }}
  {{- end }}
  hostnames:
    - {{ .Values.gatewayApi.host | quote }}
  rules:
    - backendRefs:
      - name: {{ $fullName }}
        port: {{ .Values.service.port }}

{{- end -}}
