replicaCount: 1

postgresql:
  primary:
    persistence:
      existingClaim: pg-pvc
    service:
      type: NodePort
      nodePorts:
        postgresql: 30001
  auth: 
    postgresPassword: pgpass
    username: scryuser
    password: scrypassword
    database: scry
  volumePermissions:
    enabled: true