apiVersion: v1
kind: Service
metadata:
  name: {{ include "directus-local.fullname" . }}-svc
  labels:
    {{- include "directus-local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "directus-local.selectorLabels" . | nindent 4 }}
