localDirectory: /Users/garun/code/structurizr/examples/dsl/system-catalog

replicaCount: 1

image:
  repository: structurizr/lite
  pullPolicy: IfNotPresent
  tag: "latest"

service: 
  port: 8080

ingress:
  create: false
  host: diagrams.local.scryapp.website
  annotations: {}

gatewayApi:
  create: false
  host: diagrams.local.scryapp.website
  gateway: 
    create: true
    className: cilium
    name: ""
    namespace: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

